import idautils as idautils
import idaapi
import ida_search as ida_search
import ida_funcs as ida_funcs
from iBootStrap.util import *

symbol_table = \
    {
        'start': 0x0,
        'reset': 0x0,
        'relocate_loop': 0x0,
        'relocate_data': 0x0,
        'relocate_data_loop': 0x0,
        'stack_setup': 0x0,
        'bss_loop': 0x0,
        'bss_done': 0x0,
        'spin': 0x0,
        'Description': 0x0,
        'ReleaseCategory': 0x0,
        'iBootVersion': 0x0,
        'main': 0x0,
        'Start': 0x0,
        'sram_start': 0x0,
        'argv': 0x0,
        'heap_base': 0x0,
        '_arm_read_cpsr': 0x0,
        '_arm_read_ifsr': 0x0,
        '_arm_read_dfsr': 0x0,
        '_arm_write_l2_aux_cr': 0x0,
        '_arm_read_ifar': 0x0,
        '_arm_read_extended_feature_regs': 0x0,
        '_arm_read_memory_model_feature_regs': 0x0,
        '_arm_read_instruction_set_attribute_regs': 0x0,
        '_arm_read_cr': 0x0,
        '_arm_write_cr': 0x0,
        '_arm_read_aux_cr': 0x0,
        '_arm_write_aux_cr': 0x0,
        '_arm_write_dar': 0x0,
        '_arm_write_ttb': 0x0,
        '_arm_write_ttbcr': 0x0,
        '_arm_read_dfar': 0x0,
        '_arm_read_main_id': 0x0,
        '_arm_read_cache_id': 0x0,
        '_arm_read_cache_level_id': 0x0,
        '_arm_write_user_rw_tid': 0x0,
        '_arm_read_fpexc': 0x0,
        '_arm_read_fpscr': 0x0,
        '_arm_read_cache_size_selection': 0x0,
        '_arm_write_user_ro_tid': 0x0,
        '_arm_read_pmreg': 0x0,
        '_arm_write_pmreg': 0x0,
        '_arm_read_cache_size_id': 0x0,
        '_arm_write_sup_tid': 0x0,
        '_arm_read_l2_aux_cr': 0x0,
        '_arm_write_perip_port_remap': 0x0,
        '_arm_read_user_rw_tid': 0x0,
        '_arm_write_dprot_region_8': 0x0,
        '_arm_read_user_ro_tid': 0x0,
        '_arm_write_data_prot_register': 0x0,
        '_arm_flush_tlbs': 0x0,
        '_arm_write_ins_prot_register': 0x0,
        '_arm_write_cacheable_registers': 0x0,
        '_arm_write_bufferable_register': 0x0,
        '_arch_restore_ints': 0x0,
        '_arm_enable_fiqs': 0x0,
        '_arm_disable_fiqs': 0x0,
        '_arm_read_sup_tid': 0x0,
        '_arm_write_vbar': 0x0,
        '_arm_flush_branch_predictor': 0x0,
        '_arm_memory_barrier': 0x0,
        '_arch_halt': 0x0,
        '_arch_spin': 0x0,
        '_main': 0x0,
        '_timer_get_ticks': 0x0,
        '_aic_get_ticks': 0x0,
        '_aic_spin': 0x0,
        '_timer_ticks_to_usecs': 0x0,
        '_timer_usecs_to_ticks': 0x0,
        '_timer_get_entropy': 0x0,
        '_usbphy_enable_pullup': 0x0,
        'jpt_1C84': 0x0,
        '__src': 0x0,
        '_synopsys_otg_get_connection_speed': 0x0,
        '_synopsys_otg_is_endpoint_stalled': 0x0,
        '_synopsys_otg_go_on_bus': 0x0,
        '_synopsys_otg_start_ep0_out': 0x0,
        'verify_img4_whatever': 0x0,
        'aNrpdxekeyekeorpeceseorpdtsgdlodsmodscicedicegcnbbesccescnrpcorpc': 0x0,
        'platform_cache_operation': 0x0,
        'j_j__arm_memory_barrier': 0x0,
        'j__chipid_get_minimum_epoch': 0x0,
        'platform_init_setup_clocks': 0x0,
        'platform_init_hwpins': 0x0,
        'platform_init_internal_mem': 0x0,
        'platform_quiesce_hardware': 0x0,
        'platform_bootprep': 0x0,
        'chipid_clear_production_mode': 0x0,
        '_platform_init_setup_clocks': 0x0,
        'platform_get_boot_device': 0x0,
        'jpt_53A6': 0x0,
        'def_53A6': 0x0,
        'platform_enable_boot_interface': 0x0,
        'platform_set_dfu_status': 0x0,
        'platform_get_force_dfu': 0x0,
        'platform_get_request_dfu1': 0x0,
        'platform_get_request_dfu2': 0x0,
        'platform_get_boot_trampoline': 0x0,
        '__dst': 0x0,
        '_chipid_get_production_mode': 0x0,
        '_chipid_get_security_domain': 0x0,
        '_chipid_get_board_id': 0x0,
        '_chipid_get_minimum_epoch': 0x0,
        '_charger_has_external': 0x0,
        'chipid_set_fuse_lock': 0x0,
        'jpt_5F38': 0x0,
        'def_5F38': 0x0,
        'halt': 0x0,
        'nullsub_1': 0x0,
        '_platform_power_spin': 0x0,
        'platform_watchdog_tickle': 0x0,
        '_prepare_and_jump': 0x0,
        '_callout_dequeue': 0x0,
        '_debug_init': 0x0,
        'nullsub_3': 0x0,
        '__panic': 0x0,
        'doublePanicIn': 0x0,
        'panicMacro': 0x0,
        'platform_get_usb_cable_connected': 0x0,
        '_enter_critical_section': 0x0,
        '_exit_critical_section': 0x0,
        '_task_get_current_task': 0x0,
        'list_delete': 0x0,
        'task_yield': 0x0,
        'insert_run_q_tail': 0x0,
        'task_start': 0x0,
        'task_exit': 0x0,
        'wait_queue_wake_all': 0x0,
        'wait_queue_wake_one': 0x0,
        '_list_remove_head': 0x0,
        '_deep_idle_timeout': 0x0,
        '_system_time': 0x0,
        '_time_has_elapsed': 0x0,
        '_spin': 0x0,
        'security_init': 0x0,
        '_security_set_production_override': 0x0,
        '_arm_clean_dcache_line': 0x0,
        '_arm_clean_invalidate_dcache_line': 0x0,
        '_arm_clean_invalidate_dcache': 0x0,
        '_arm_clean_dcache': 0x0,
        '_arm_invalidate_dcache': 0x0,
        '_arm_invalidate_icache': 0x0,
        '_arm_drain_write_buffer': 0x0,
        '_arm_mmu_map_section_range': 0x0,
        'jpt_731C': 0x0,
        'def_731C': 0x0,
        '_arm_mmu_init': 0x0,
        '_arm_fp_init': 0x0,
        'arch_cpu_init': 0x0,
        '_arch_cpu_quiesce': 0x0,
        '_clocks_init': 0x0,
        '_arch_get_entropy': 0x0,
        'arm_irq': 0x0,
        'arm_fiq': 0x0,
        'arm_undefined': 0x0,
        'arm_syscall': 0x0,
        'arm_prefetch_abort': 0x0,
        'arm_data_abort': 0x0,
        '___arm_reserved': 0x0,
        '_usb_init_with_controller': 0x0,
        '_usb_init': 0x0,
        '_usb_quiesce': 0x0,
        '_usb_free': 0x0,
        '_usb_controller_register': 0x0,
        '__b': 0x0,
        '_usb_controller_stop': 0x0,
        '_usb_controller_deactivate_endpoint': 0x0,
        '_stdout_outfunc': 0x0,
        'usb_create_string_descriptor': 0x0,
        'jpt_81D2': 0x0,
        'jpt_82D2': 0x0,
        'def_81D2': 0x0,
        '_usb_core_free': 0x0,
        '_getDFUImage': 0x0,
        '_usb_dfu_init': 0x0,
        '_usb_dfu_exit': 0x0,
        'image_load': 0x0,
        '_siphash_aligned': 0x0,
        'def_945E': 0x0,
        'jpt_945E': 0x0,
        '_required_size': 0x0,
        '_verify_block_checksum': 0x0,
        '_heap_free': 0x0,
        '_calculate_block_checksum': 0x0,
        '_heap_memalign': 0x0,
        '_alloc_ep0_device_io_request': 0x0,
        '_heap_panic': 0x0,
        '_verify_block_padding': 0x0,
        '_free_list_add': 0x0,
        'heap_verify': 0x0,
        'j__heap_free': 0x0,
        'jpt_A012': 0x0,
        'def_A012': 0x0,
        'jpt_A094': 0x0,
        '_vsnprintf': 0x0,
        '_longlong_to_hexstring': 0x0,
        'kAsciiHexChars': 0x0,
        '___vsnprintf_chk': 0x0,
        '_puts': 0x0,
        '_putchar': 0x0,
        '___strlcat_chk': 0x0,
        '___stack_chk_fail': 0x0,
        '_memcpy': 0x0,
        '_memset': 0x0,
        '_bzero': 0x0,
        '_strlen': 0x0,
        '_amc_phy_run_dll_update': 0x0,
        '_strlcat': 0x0,
        '_strlcpy': 0x0,
        '_DERParseBitString': 0x0,
        '_DERParseBoolean': 0x0,
        '_DERParseInteger': 0x0,
        '_DERParseInteger64': 0x0,
        '_DERDecodeSeqInit': 0x0,
        '_DERDecodeSeqContentInit': 0x0,
        '_DERDecodeSeqNext': 0x0,
        '_DERParseSequence': 0x0,
        '_DERParseSequenceContent': 0x0,
        '_Img4DecodeParseLengthFromBuffer': 0x0,
        '_random_get_bytes': 0x0,
        '_mib_get_u32': 0x0,
        '_random_get_bytes_internal': 0x0,
        '_random_get_bytes_noheap': 0x0,
        '_chipid_get_current_production_mode': 0x0,
        '_platform_get_raw_production_mode': 0x0,
        '_platform_get_security_domain': 0x0,
        'j__chipid_get_minimum_epoch_0': 0x0,
        '_platform_get_chip_id': 0x0,
        '_platform_get_ecid_image_personalization_required': 0x0,
        '_platform_get_entropy': 0x0,
        '_platform_get_usb_vendor_id': 0x0,
        '_power_needs_precharge': 0x0,
        '_platform_halt': 0x0,
        '_platform_deep_idle': 0x0,
        '_platform_get_usb_manufacturer_string': 0x0,
        '_platform_get_usb_device_version': 0x0,
        '_platform_get_fuse_modes': 0x0,
        '_DERImg4DecodeFindInSequence': 0x0,
        '_DERImg4DecodeContentFindItemWithTag': 0x0,
        '_DERImg4DecodeTagCompare': 0x0,
        '_DERImg4Decode': 0x0,
        '_DERImg4DecodeUnsignedManifest': 0x0,
        '_Img4DecodeInitUnsignedManifest': 0x0,
        '_Img4DecodeGetBooleanFromSection': 0x0,
        '_Img4DecodeGetPropertyFromSection': 0x0,
        '_Img4DecodeGetPropertyBoolean': 0x0,
        '_Img4DecodeEvaluateCertificateProperties': 0x0,
        '_Img4DecodeEvaluateDictionaryProperties': 0x0,
        '_arch_get_entropy$shim': 0x0,
        'j__arm_clean_invalidate_dcache': 0x0,
        '_arm_clean_invalidate_dcache_line_2': 0x0,
        'j__arm_clean_dcache': 0x0,
        '_platform_get_chip_revision': 0x0,
        '_arm_flush_tlbs$shim': 0x0,
        '_arm_write_cp_access_cr$shim': 0x0,
        'j__arm_enable_fiqs': 0x0,
        '_strlen$shim': 0x0,
        '_arch_halt$shim': 0x0,
        '_synopsys_otg_free': 0x0,
        '_arm_read_perip_port_remap': 0x0,
        '_arm_read_vbar': 0x0,
        'current_task': 0x0,
        'ebolink': 0x0,
    }



def find_string_ref(string: str, base_ea):
    panic_ea = BADADDR
    pk_ea = ida_search.find_text(base_ea, 1, 1, "double panic in ", ida_search.SEARCH_DOWN)

    if bad(pk_ea):
        print("\t[-] Panic string not found")
        return BADADDR

    if pk_ea < base_ea:  # String is in func
        panic_ea = idaapi.get_func(pk_ea)

    for xref in idautils.XrefsTo(pk_ea):
        func = idaapi.get_func(xref.frm)
        if not func:
            continue
        panic_ea = func.start_ea

    if bad(pk_ea):
        print("\t[-] _panic = not found")
        return BADADDR

    print(f'\t[+] _panic = 0x{panic_ea}')
    set_name(panic_ea, "_panic", SN_CHECK)
    return panic_ea
